/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


import Modelo.Categoria;
import Modelo.DetallePedido;

import Modelo.Mesa;
import Modelo.MesaDAO;
import Modelo.Pedido;
import Modelo.PedidoDAO;
import Modelo.Producto;
import Modelo.ProductoDAO;
import br.com.adilson.util.Extenso;
import br.com.adilson.util.PrinterMatrix;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Cristian
 */
public class Pedidos extends javax.swing.JInternalFrame {

    
    MesaDAO dao= new MesaDAO();
    Mesa me = new Mesa();
    DefaultTableModel modelo = new DefaultTableModel();
    Pedido pe = new Pedido();
    DetallePedido dp = new DetallePedido();
    PedidoDAO ped = new PedidoDAO();
    Calendar fecha_actual = new GregorianCalendar();
    Producto pro = new Producto();
    ProductoDAO prod = new ProductoDAO();
    TableRowSorter<DefaultTableModel> sorter;
    
    
    int id;
    int item = 0;
    int cantTotal;
    double ttotal;
    double preTotal;
    int idMesa;
    int idImpresora;
    int fila;//para capturar fila seleccionada de talba productos 
    boolean existeComida = false;
    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        
        initComponents();
        
        CampoNMesa.setText(PedidoMesa.mes);
        CampoNMesa.setEditable(false);
        CampoMozo.requestFocus();
        CampoCodigo.setEditable(false);
        CampoPrecio.setEditable(false);
        CampoProducto.setEditable(false);
        if(PedidoMesa.mes.equals("")){
            idMesa=0;
        }else{
            idMesa=dao.IdMesa(PedidoMesa.mes);

        }
        listar();
        jTextField1.requestFocus();
        
        

    }
    
    void listar(){
        List<Producto> lista=prod.listar();
        List<Categoria> listac = prod.listarCat();
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
        TablaProductos2.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(modelo); 
        TablaProductos2.setRowSorter(sorter);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CampoNMesa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoMozo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CampoTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ButtonGenerarPedido = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CampoProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CampoPrecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        SnipperCantidad = new javax.swing.JSpinner();
        ButtonAgregar = new javax.swing.JButton();
        ButtonQuitar = new javax.swing.JButton();
        ButtonModificar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CampoEspecificaciones = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CevichesButton = new javax.swing.JButton();
        PiqueosButton = new javax.swing.JButton();
        ChicharronesButton = new javax.swing.JButton();
        ArrocesButton = new javax.swing.JButton();
        CriolloButton = new javax.swing.JButton();
        CaldosButton = new javax.swing.JButton();
        BebidasButton = new javax.swing.JButton();
        BarButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setClosable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("PEDIDOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("NUMERO DE MESA:");

        CampoNMesa.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        CampoNMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNMesaActionPerformed(evt);
            }
        });

        jLabel4.setText("MOZO:");

        CampoMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoMozoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CampoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTotalActionPerformed(evt);
            }
        });

        jLabel11.setText("TOTAL A PAGAR:");

        ButtonGenerarPedido.setBackground(new java.awt.Color(102, 255, 0));
        ButtonGenerarPedido.setText("COMANDAR");
        ButtonGenerarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGenerarPedidoActionPerformed(evt);
            }
        });

        ButtonCancelar.setBackground(new java.awt.Color(255, 51, 0));
        ButtonCancelar.setText("CANCELAR");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonGenerarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonGenerarPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "COD", "PRODUCTO", "CANTIDAD", "PRE UNI", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.setRowHeight(40);
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setPreferredWidth(5);
            TablaProductos.getColumnModel().getColumn(1).setPreferredWidth(5);
            TablaProductos.getColumnModel().getColumn(2).setPreferredWidth(200);
            TablaProductos.getColumnModel().getColumn(3).setPreferredWidth(10);
            TablaProductos.getColumnModel().getColumn(4).setPreferredWidth(10);
            TablaProductos.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("COD. PRODUC:");

        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });

        jLabel13.setText("PRODUCTO:");

        jLabel14.setText("PRECIO:");

        jLabel15.setText("CANTIDAD:");

        SnipperCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SnipperCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        SnipperCantidad.setToolTipText("");
        SnipperCantidad.setEditor(new javax.swing.JSpinner.NumberEditor(SnipperCantidad, ""));
        SnipperCantidad.setValue(1);
        SnipperCantidad.setVerifyInputWhenFocusTarget(false);

        ButtonAgregar.setText("AGREGAR");
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });

        ButtonQuitar.setText("QUITAR");
        ButtonQuitar.setEnabled(false);
        ButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQuitarActionPerformed(evt);
            }
        });

        ButtonModificar.setText("MODIFICAR");
        ButtonModificar.setEnabled(false);
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });

        CampoEspecificaciones.setColumns(20);
        CampoEspecificaciones.setRows(5);
        jScrollPane3.setViewportView(CampoEspecificaciones);

        jLabel17.setText("ESPECIFICACIONES DEL PEDIDO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(365, 365, 365))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SnipperCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(ButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonModificar)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CampoPrecio)
                                                .addGap(102, 102, 102))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CampoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jScrollPane3))
                                        .addContainerGap())))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CampoMozo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoNMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(CampoNMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoMozo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CampoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(CampoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(ButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SnipperCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("CATEGORIAS");

        CevichesButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        CevichesButton.setText("CEVICHES Y FRIOS");
        CevichesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CevichesButtonActionPerformed(evt);
            }
        });

        PiqueosButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        PiqueosButton.setText("PIQUEOS");
        PiqueosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiqueosButtonActionPerformed(evt);
            }
        });

        ChicharronesButton.setText("CHICHARRONES Y PESCADOS");
        ChicharronesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicharronesButtonActionPerformed(evt);
            }
        });

        ArrocesButton.setText("ARROCES Y PASTAS");
        ArrocesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrocesButtonActionPerformed(evt);
            }
        });

        CriolloButton.setText("CRIOLLO");
        CriolloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriolloButtonActionPerformed(evt);
            }
        });

        CaldosButton.setText("CALDOS Y CHUPES");
        CaldosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaldosButtonActionPerformed(evt);
            }
        });

        BebidasButton.setText("BEBIDAS");
        BebidasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasButtonActionPerformed(evt);
            }
        });

        BarButton.setText("BAR");
        BarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(58, 58, 58))
            .addComponent(ChicharronesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PiqueosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CevichesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ArrocesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CriolloButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CaldosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BebidasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CevichesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PiqueosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChicharronesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArrocesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CriolloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CaldosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BebidasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setText("PRODUCTOS");

        TablaProductos2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TablaProductos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIPCION", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos2.setRowHeight(40);
        TablaProductos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductos2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProductos2);
        if (TablaProductos2.getColumnModel().getColumnCount() > 0) {
            TablaProductos2.getColumnModel().getColumn(0).setPreferredWidth(5);
            TablaProductos2.getColumnModel().getColumn(1).setPreferredWidth(250);
            TablaProductos2.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setText("ATRAS <-");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(473, 473, 473))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        // TODO add your handling code here:
        
        if(CampoCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "No selecciono producto");
            
        }else{
            agregarProducto();
            SnipperCantidad.setValue(1);
            CampoProducto.setText("");
            CampoPrecio.setText("");
            CampoCodigo.setText("");   
        }
        jTextField1.setText("");
        limpiarTabla();
        listar();
    }//GEN-LAST:event_ButtonAgregarActionPerformed
    
    void limpiarTabla(){
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        for(int i=0; i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;  
        }
    }
    
    void agregarProducto()
    {        
        item++;
        modelo=(DefaultTableModel)TablaProductos.getModel();
        String ids=CampoCodigo.getText();
        String nomb= CampoProducto.getText();
        double pre=Double.parseDouble(CampoPrecio.getText());
        int cant = Integer.parseInt(SnipperCantidad.getValue().toString());
        double total=pre*cant;
        
        ArrayList lista = new ArrayList();
        lista.add(item);
        lista.add(ids);
        lista.add(nomb);
        lista.add(cant);
        lista.add(pre);
        lista.add(total);
        Object[] ob = new Object[6];
        ob[0]=lista.get(0);
        ob[1]=lista.get(1);
        ob[2]=lista.get(2);
        ob[3]=lista.get(3);
        ob[4]=lista.get(4);
        ob[5]=lista.get(5);
        modelo.addRow(ob);
        TablaProductos.setModel(modelo);
        CalcularTotal();
    }
    
    void CalcularTotal(){
         ttotal=0;
         for(int i=0; i<TablaProductos.getRowCount();i++){
             cantTotal = Integer.parseInt(TablaProductos.getValueAt(i, 3).toString());
             preTotal = Double.parseDouble(TablaProductos.getValueAt(i, 4).toString());
             ttotal=ttotal+cantTotal*preTotal;
         } 
         
         CampoTotal.setText(""+ttotal);
    }
    
    
    private void ButtonGenerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGenerarPedidoActionPerformed
        // TODO add your handling code here:
        if(CampoMozo.getText().equals("") || TablaProductos.getRowCount()==0 ){
           JOptionPane.showMessageDialog(this, "INGRESE DATOS DEL MOZO"); 
        }else{
            guardarPedidoComanda();
            guardarDetallePedido();        
            JOptionPane.showMessageDialog(this, "PEDIDO AGREGADO CON EXITO");
            actualizarMesaBar();//cambio por el segundo actualizar para que no aparezca en comanda virtual 
            if(existeComida==true){
                imprimirboucher();
            }
            
            dispose(); 
        }
        
       
        
         
       
    }//GEN-LAST:event_ButtonGenerarPedidoActionPerformed
    
    void imprimirboucher(){
            try {
                 int lineCount = CampoEspecificaciones.getLineCount();
                File archivo;
                archivo = new File("C:\\temp2\\pedido"+ped.IdPedido()+".txt");

                PrinterMatrix printer = new PrinterMatrix();
                Extenso e = new Extenso();

                e.setNumber(20.30);
                //Definir el tamanho del papel para la impresion de dinamico y 32 columnas
                int filas = TablaProductos.getRowCount();
                int tamaño = filas+17+lineCount;
                printer.setOutSize(tamaño, 45);

                //Imprimir = 1ra linea de la columa de 1 a 32

                printer.printTextWrap(1, 1, 15, 45, "Nro Pedido: "+String.valueOf(ped.IdPedido())); //Nombre establecimiento
                printer.printTextWrap(3, 1, 1, 45, "MESA:"+CampoNMesa.getText()+" MOZO:"+CampoMozo.getText() ); //Barrio
                Date dd = new Date();
                SimpleDateFormat datef = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat timef = new SimpleDateFormat("HH:mm:ss");
                String date= datef.format(dd);
                String time= timef.format(dd);
                printer.printTextWrap(3, 1, 25, 45, date +" "+ time); //Direccion
                printer.printTextWrap(4, 1, 1, 45, "============================================");              
                printer.printTextWrap(5,1, 1, 45, "DESCRIPCION                            CANT");
                printer.printTextWrap(6,1, 0, 40, " ");

                for (int i = 0; i < filas; i++) {
                    int p = 7+i; //Fila


                    printer.printTextWrap(p , 1, 1, 41 , TablaProductos.getValueAt(i,2).toString());
                    printer.printTextWrap(p , 1, 42, 45, TablaProductos.getValueAt(i,3).toString());

                    

                    //String inp= printer.alinharADireita(7,punto_Venta.jtbl_venta.getValueAt(i,6).toString());
                    //printer.printTextWrap(p , 1, 25, 32, inp);
                }

                printer.printTextWrap(filas+9,1, 1, 45, "============================================");
                printer.printTextWrap(filas+10,1, 10, 45, "ESPECIFICACIONES");
                
               
                String[] lines = new String[lineCount];
                String text = CampoEspecificaciones.getText();
                for (int i = 0; i < lineCount; ++i) {
                    int offset = CampoEspecificaciones.getLineStartOffset(i);
                    int offset2 = CampoEspecificaciones.getLineEndOffset(i);
                    lines[i] = text.substring(offset, offset2);
                    printer.printTextWrap(filas+11+i,1, 1, 45, text.substring(offset, offset2));
                }
                
                //printer.printTextWrap(filas+11,1, 1, 45, CampoEspecificaciones.getText());
                
                ///CREAR ARCHIVO EN CARPETA DEL PROYECTO PARA PEDIDOS
                printer.toFile("C:\\temp2\\pedido"+ped.IdPedido()+".txt");
                FileInputStream inputStream = null;

            try {
                inputStream = new FileInputStream("C:\\temp2\\pedido"+ped.IdPedido()+".txt");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }
            if (inputStream == null) {
                return;
            }
            
            DocFlavor docFormat = DocFlavor.INPUT_STREAM.AUTOSENSE;
            Doc document = new SimpleDoc(inputStream, docFormat, null);
            PrintRequestAttributeSet attributeSet = new HashPrintRequestAttributeSet();
            PrintService [] printService = PrintServiceLookup.lookupPrintServices(docFormat, null);
            int i =0;
            for(PrintService service : printService){
                System.out.println("Impresora"+i+" : "+service.getName());
                if(service.getName().equals("BASIC 240")){
                    idImpresora = i;
                }
                i++;
            }
            
            //PrintService defaultPrintService = PrintServiceLookup.lookupDefaultPrintService();

            if (printService[idImpresora] != null) {
                DocPrintJob printJob = printService[idImpresora].createPrintJob();
                System.out.println("Se imprimio en la impresora:  "+printService[idImpresora].getName());
                //DocPrintJob printJob = defaultPrintService.createPrintJob();
                try {
                    printJob.print(document, attributeSet);
                } catch (Exception ex) {
                   ex.printStackTrace();
                }
            } else {
                System.err.println("No existen impresoras instaladas");
        }

        inputStream.close();
        //imprimirFin(subTotal, total, dineroR, devolucion); //ESTE METODO NO SE UTILIZARA
    
        DocPrintJob job = PrintServiceLookup.lookupDefaultPrintService().createPrintJob();  
        byte[] bytes = {27, 100, 3};
        DocFlavor flavor = DocFlavor.BYTE_ARRAY.AUTOSENSE;
        Doc doc = new SimpleDoc(bytes, flavor, null);
        job.print(doc, null);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al imprimir "+e);
    }
    
    }
    
    
    
    
    void guardarPedidoComanda(){
       double total=ttotal;
       
       int mesa = idMesa;
       int esped = 2;//cambio para no pasar por comanda virtual 
       String mozo = CampoMozo.getText();
       String especif = CampoEspecificaciones.getText();
       String es = "A";
       
       pe.setTotal(total);
       pe.setMesa(mesa);
       pe.setEsPedido(esped);
       pe.setMozo(mozo);
       pe.setEspecificaciones(especif);
       pe.setEstado(es);
       
       if(idMesa!=0){
        Object[] obj=new Object[6];
        obj[0]= total;   
        obj[1]= mesa; 
        obj[2]= esped;
        obj[3]= mozo;
        obj[4]= especif;
        obj[5]= es;
       
       
        ped.GuardarPedido(obj);   
       }else{
           Object[] obj=new Object[5];
            obj[0]= total;    
            obj[1]= esped;
            obj[2]= mozo;
            obj[3]= especif;
            obj[4]= es;
            ped.GuardarPedidoLlevar(obj);
       }
       
       
       
    }
    
    void guardarDetallePedido(){
        
        
        int idve = Integer.parseInt(ped.IdPedido());
        for(int i = 0; i<TablaProductos.getRowCount();i++){
            int idp = Integer.parseInt(TablaProductos.getValueAt(i,1).toString());
            
            int cant = Integer.parseInt(TablaProductos.getValueAt(i,3).toString());
            double pre = Double.parseDouble(TablaProductos.getValueAt(i, 5).toString());
            String es = "A";
            
            dp.setDetallePed(idve);
            dp.setIdProducto(idp);
            dp.setCantidad(cant);
            dp.setTotal(pre);
            dp.setEstado(es);
            //dp.setFecha(fecha_actual.getCalendarType());
            ped.GuardarDetallePedido(dp); 
            
            
            
            if(prod.getCat(idp)==8){
                   
                int stock = prod.getStock(idp);
                System.out.print(stock);
                prod.actualizarStock(idp, stock-cant);
            }else{
                existeComida=true; 
            }                      
        }   
    }
    
    void actualizarMesa(){
        if (idMesa!=0){
           dao.actualizarId(idMesa);  
        }
      
    }
    void actualizarMesaBar(){
        if (idMesa!=0){
           dao.actualizarIdBar(idMesa);  
        }
      
    }
    
    private void CampoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTotalActionPerformed

    private void CampoMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoMozoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoMozoActionPerformed

    private void CampoNMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNMesaActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void CriolloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriolloButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(5);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
    }//GEN-LAST:event_CriolloButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CaldosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaldosButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(6);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
    }//GEN-LAST:event_CaldosButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void BebidasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(7);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
    }//GEN-LAST:event_BebidasButtonActionPerformed

    private void BarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(8);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
    }//GEN-LAST:event_BarButtonActionPerformed

    private void CevichesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CevichesButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(1);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);   
        
        
        
    }//GEN-LAST:event_CevichesButtonActionPerformed

    private void PiqueosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiqueosButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(2);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
        
    }//GEN-LAST:event_PiqueosButtonActionPerformed

    private void ChicharronesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicharronesButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(3);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
    }//GEN-LAST:event_ChicharronesButtonActionPerformed

    private void ArrocesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrocesButtonActionPerformed
        // TODO add your handling code here:
        limpiar();
        
        List<Producto> lista=prod.listarProxCat(4);
        
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        Object[]ob=new Object[3];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();        
            modelo.addRow(ob);
        }
        TablaProductos2.setModel(modelo);
    }//GEN-LAST:event_ArrocesButtonActionPerformed

    private void TablaProductos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductos2MouseClicked
        // TODO add your handling code here:
        int fila2 = TablaProductos2.getSelectedRow();
        if(fila2==-1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila");
            
        }else {
            Pedidos.CampoCodigo.setText(TablaProductos2.getValueAt(fila2, 0).toString());
            Pedidos.CampoProducto.setText(TablaProductos2.getValueAt(fila2, 1).toString());
            Pedidos.CampoPrecio.setText(TablaProductos2.getValueAt(fila2, 2).toString());
          
            
                  
        }
       
    }//GEN-LAST:event_TablaProductos2MouseClicked

    private void ButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQuitarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel)TablaProductos.getModel();
        modelo.removeRow(fila);
        
        TablaProductos.clearSelection();
        ButtonModificar.setEnabled(false);
        ButtonQuitar.setEnabled(false);
        ButtonAgregar.setEnabled(true);
        
        SnipperCantidad.setValue(1);
        CampoProducto.setText("");
        CampoPrecio.setText("");
        CampoCodigo.setText("");
        CalcularTotal();
        
    }//GEN-LAST:event_ButtonQuitarActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        // TODO add your handling code here:
        String precio = SnipperCantidad.getValue().toString();
        double pre=Double.parseDouble(CampoPrecio.getText());
        int cant = Integer.parseInt(SnipperCantidad.getValue().toString());
        double t= pre*cant;
        TablaProductos.setValueAt(t, fila, 5);
        TablaProductos.setValueAt(precio, fila, 3);
        TablaProductos.clearSelection();
        ButtonModificar.setEnabled(false);
        ButtonQuitar.setEnabled(false);
        ButtonAgregar.setEnabled(true);
        
        SnipperCantidad.setValue(1);
        CampoProducto.setText("");
        CampoPrecio.setText("");
        CampoCodigo.setText(""); 
        CalcularTotal();
    }//GEN-LAST:event_ButtonModificarActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        // TODO add your handling code here:
        ButtonModificar.setEnabled(true);
        ButtonQuitar.setEnabled(true);
        
        fila = TablaProductos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila");
            
        }else {
            
            String ids = TablaProductos.getValueAt(fila, 1).toString();
            String nom= TablaProductos.getValueAt(fila, 2).toString();
            String precio= TablaProductos.getValueAt(fila, 4).toString();
            int cant= Integer.parseInt(TablaProductos.getValueAt(fila, 3).toString());
            
            
            CampoCodigo.setText(ids);
            CampoProducto.setText(nom);
            
            CampoPrecio.setText(precio);
            SnipperCantidad.setValue(cant);
            
           
            
            
        }
        ButtonAgregar.setEnabled(false);
        
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            
            evt.setKeyChar(Character.toUpperCase(c));
        }
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        PedidoMesa ve = new PedidoMesa();
        Menu.VentanaPrincipal.add(ve);
        ve.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    void filtrar(){
        
        try{
           sorter.setRowFilter(RowFilter.regexFilter(jTextField1.getText(), 1));
        }catch(Exception e){
            
        }
    }
    void limpiar(){
        modelo=(DefaultTableModel)TablaProductos2.getModel();
        for(int i=0; i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;  
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArrocesButton;
    private javax.swing.JButton BarButton;
    private javax.swing.JButton BebidasButton;
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonGenerarPedido;
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JButton ButtonQuitar;
    private javax.swing.JButton CaldosButton;
    public static javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextArea CampoEspecificaciones;
    private javax.swing.JTextField CampoMozo;
    private javax.swing.JTextField CampoNMesa;
    public static javax.swing.JTextField CampoPrecio;
    public static javax.swing.JTextField CampoProducto;
    private javax.swing.JTextField CampoTotal;
    private javax.swing.JButton CevichesButton;
    private javax.swing.JButton ChicharronesButton;
    private javax.swing.JButton CriolloButton;
    private javax.swing.JButton PiqueosButton;
    private javax.swing.JSpinner SnipperCantidad;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TablaProductos2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
