/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Categoria;
import Modelo.Producto;
import Modelo.ProductoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class Productos extends javax.swing.JInternalFrame {
    
    
    
    ProductoDAO dao = new ProductoDAO();
    Producto pro = new Producto();
    DefaultTableModel modelo = new DefaultTableModel();
    int id;
    

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        listar();
        llenarCategorias();
        
        ActualizarButton.setEnabled(false);
        EliminarButton.setEnabled(false);
        NuevoButton.setEnabled(false);
        CampoStock.setEnabled(false);
    }
    
    void listar(){
        List<Producto> lista=dao.listar();
        List<Categoria> listac = dao.listarCat();
        modelo=(DefaultTableModel)TablaProductos.getModel();
        Object[]ob=new Object[7];
        for(int i=0;i<lista.size();i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNom();
            ob[2]=lista.get(i).getPrec();
            ob[3]=listac.get(lista.get(i).getCat()-1).getNombreCat();
            ob[4]=lista.get(i).getStock();
            ob[5]=lista.get(i).getEstado();
            ob[6]=lista.get(i).getDes();
            modelo.addRow(ob);
        }
        TablaProductos.setModel(modelo);
    }
    
    void llenarCategorias(){
        CategoriaBox.removeAllItems();
        List<Categoria> listac = dao.listarCat();
        for(int i=0;i<listac.size();i++){ 
            CategoriaBox.addItem(listac.get(i).getNombreCat());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoDescripcion = new javax.swing.JTextArea();
        CampoPrecio = new javax.swing.JTextField();
        CategoriaBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        EstadoBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AgregarButton = new javax.swing.JButton();
        ActualizarButton = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();
        NuevoButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CampoStock = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("NOMBRE DE PRODUCTO:");

        jLabel3.setText("DESCRIPCION DEL PRODUCTO:");

        jLabel4.setText("PRECIO DEL PRODUCTO:");

        jLabel5.setText("CATEGORIA DEL PRODUCTO:");

        CampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreActionPerformed(evt);
            }
        });

        CampoDescripcion.setColumns(20);
        CampoDescripcion.setRows(5);
        jScrollPane1.setViewportView(CampoDescripcion);

        CampoPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoPrecioKeyTyped(evt);
            }
        });

        CategoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CategoriaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("ESTADO:");

        EstadoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "I" }));

        jLabel7.setText("A = Activo");

        jLabel8.setText("I = Inactivo");

        AgregarButton.setText("AGREGAR");
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });

        ActualizarButton.setText("ACTUALIZAR");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });

        EliminarButton.setText("ELIMINAR");
        EliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarButtonActionPerformed(evt);
            }
        });

        NuevoButton.setText("NUEVO");
        NuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("STOCK:");

        CampoStock.setText("0");
        CampoStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoStockKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CampoPrecio)
                        .addComponent(CampoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(CategoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ActualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NuevoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EstadoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CampoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EstadoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarButton)
                    .addComponent(NuevoButton))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE ", "PRECIO ", "CATEGORIA", "STOCK", "ESTADO REGISTRO", "DESCRIPCION"
            }
        ));
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setPreferredWidth(25);
            TablaProductos.getColumnModel().getColumn(1).setPreferredWidth(150);
            TablaProductos.getColumnModel().getColumn(2).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(3).setPreferredWidth(100);
            TablaProductos.getColumnModel().getColumn(4).setPreferredWidth(40);
            TablaProductos.getColumnModel().getColumn(5).setPreferredWidth(25);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreActionPerformed

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        // TODO add your handling code here:
        agregar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        // TODO add your handling code here:\
        AgregarButton.setEnabled(true);
        ActualizarButton.setEnabled(false);
        EliminarButton.setEnabled(false);
        NuevoButton.setEnabled(false);
        actualizar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
        // TODO add your handling code here:
        AgregarButton.setEnabled(true);
        ActualizarButton.setEnabled(false);
        EliminarButton.setEnabled(false);
        NuevoButton.setEnabled(false);
        eliminar();
        limpiarTabla();
        listar();
        nuevo();

    }//GEN-LAST:event_EliminarButtonActionPerformed

    private void NuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoButtonActionPerformed
        // TODO add your handling code here:
        nuevo();
        AgregarButton.setEnabled(true);
        ActualizarButton.setEnabled(false);
        EliminarButton.setEnabled(false);
        NuevoButton.setEnabled(false);
    }//GEN-LAST:event_NuevoButtonActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        // TODO add your handling code here:
        int fila = TablaProductos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila");
            
        }else {
            id = Integer.parseInt(TablaProductos.getValueAt(fila, 0).toString());
            String nom= TablaProductos.getValueAt(fila, 1).toString();
            String precio= TablaProductos.getValueAt(fila, 2).toString();
            String cat= TablaProductos.getValueAt(fila, 3).toString();
            String es= TablaProductos.getValueAt(fila, 5).toString();
            String st = TablaProductos.getValueAt(fila, 4).toString();
            String des=TablaProductos.getValueAt(fila, 6).toString();
            
            CampoNombre.setText(nom);
            CampoPrecio.setText(precio);
            CategoriaBox.setSelectedItem(cat);
            EstadoBox.setSelectedItem(es);
            CampoDescripcion.setText(des);
            CampoStock.setText(st);
            
            ActualizarButton.setEnabled(true);
            EliminarButton.setEnabled(true);
            AgregarButton.setEnabled(false);
            NuevoButton.setEnabled(true);
            
            
        } 
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void CampoPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPrecioKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_CampoPrecioKeyTyped

    private void CampoStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoStockKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_CampoStockKeyTyped

    private void CategoriaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaBoxActionPerformed

    void agregar(){
        if(CampoNombre.getText().length()==0 || CampoPrecio.getText().length()==0 ){
            JOptionPane.showMessageDialog(this, "Debe llenar los campos");
        }else{
            List<Categoria> listac = dao.listarCat();
            String nombrePro = CampoNombre.getText();
            String precio = CampoPrecio.getText();
            String des = CampoDescripcion.getText();
            String es = EstadoBox.getSelectedItem().toString();
            String st = CampoStock.getText();
            int cat = listac.get(CategoriaBox.getSelectedIndex()).getId();
            
            Object[] ob= new Object[6];
            ob[0]=nombrePro;
            ob[1]=des;
            ob[2]=precio;
            ob[3]=cat;
            ob[4]=es;
            ob[5]=st;
            dao.add(ob);
        }
    }
    
    void actualizar(){
        int fila = TablaProductos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila");
        }else{
            
            List<Categoria> listac = dao.listarCat();
            String nombrePro = CampoNombre.getText();
            String precio = CampoPrecio.getText();
            String des = CampoDescripcion.getText();
            String es = EstadoBox.getSelectedItem().toString();
            String st = CampoStock.getText();
            int cat = listac.get(CategoriaBox.getSelectedIndex()).getId();
            
            Object[] ob= new Object[7];
            ob[0]=nombrePro;
            ob[1]=des;
            ob[2]=precio;
            ob[3]=cat;
            ob[4]=es;
            ob[5]=st;
            ob[6]=id;
            dao.actualizar(ob);
       
        }
        
    }
    
    void eliminar(){
        int fila = TablaProductos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila");
        }else{
            String es = "*";
            Object[] obj=new Object[2];
            obj[0]= es;
            obj[1]= id;
            dao.eliminar(obj);
        }
    }
    
    void nuevo(){
        CampoNombre.setText("");
        CampoDescripcion.setText("");
        CampoPrecio.setText("");
        CampoStock.setText("0");
        EstadoBox.setSelectedIndex(0);
        CategoriaBox.setSelectedIndex(0);
        CampoNombre.requestFocus();
        
    }
    void limpiarTabla(){
        for(int i=0; i<modelo.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;  
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton AgregarButton;
    private javax.swing.JTextArea CampoDescripcion;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoPrecio;
    private javax.swing.JTextField CampoStock;
    private javax.swing.JComboBox<String> CategoriaBox;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JComboBox<String> EstadoBox;
    private javax.swing.JButton NuevoButton;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
